# Linear Algebra
These examples are based on numpy, linear algebra library [numpy.linalg](https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html) and [scipy.linalg](https://docs.scipy.org/doc/scipy-0.15.1/reference/linalg.html)

## Basic

In [104]:
import numpy as np
import scipy
# scalar
3
# vector
np.array([1,2,3]).reshape([3, 1])

array([[1],
       [2],
       [3]])

In [105]:
# matrix
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
# matrix transpose
np.transpose(m) # or m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [107]:
# tennsor
# for example: NHWC image representation

In [108]:
# matrix multiplying
m_1 = np.array([[1, 2], [1, 2]])
m_2 = np.array([[3, 4], [3, 4]])
m_1 * m_2 # elementwise product

array([[3, 8],
       [3, 8]])

In [109]:
np.dot(m_1, m_2)

array([[ 9, 12],
       [ 9, 12]])

In [110]:
# identity matrix
np.identity(3) # equal to np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [111]:
# inverse matrix
a = np.array([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a)
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [112]:
np.dot(a, a_inv) # output should be identity matrix

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [113]:
np.allclose(np.dot(a, a_inv), np.eye(2))

True

In [114]:
np.allclose(np.dot(a_inv, a), np.eye(2))

True

    Ax = b has a solution <=> rank(A,b) = rank(A) <=> b belongs to column space
    matrix rank == range of column space == range of row space

In [115]:
# get matrix rank by SVD
np.linalg.matrix_rank(a)

2

In [116]:
# norms
a = np.array([[1, 2], [3, 4]])
np.linalg.norm(a) # defaults to L2 norm(Frobenius norm)

5.4772255750516612

In [117]:
# L1 norm
np.linalg.norm(a, ord=1)

6.0

In [118]:
# L infinity
np.linalg.norm(a, ord=np.inf)

7.0

## Special Kinds of Matrices and Vectors
* diagonal matrix
* symmetric matrix  (A == A<sup>T</sup>)
* unit vector
* orthogonal matrix (AA<sup>T</sup> == A<sup>T</sup>A == IdentityMatrix)

In [119]:
# Diagonal matrices
diag_1 = np.diag([3, 4])
diag_1

array([[3, 0],
       [0, 4]])

In [120]:
diag_v = np.diagonal(diag_1) # get diagonal value
diag_v

array([3, 4])

In [121]:
# symmetric matrix
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
sym_mat = np.tril(a) + np.tril(a, -1).T
sym_mat

array([[1, 4, 7],
       [4, 5, 8],
       [7, 8, 9]])

In [122]:
sym_mat == sym_mat.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [123]:
# unit vector
a = np.array([1, 2, 3])
unit_vec = a / np.sqrt(np.sum(a ** 2))
np.linalg.norm(unit_vec)  # L2 norm of unit vector should be one.

1.0

In [131]:
# orthogonal matrix
a = np.array([[1,2],[3,4]])
orth_1 = scipy.linalg.orth(a)
orth_1

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

In [132]:
np.dot(orth_1, orth_1.T) == np.dot(orth_1.T, orth_1)

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [134]:
np.allclose(np.dot(orth_1, orth_1.T), np.identity(2))

True

## Matrix Decomposition
### Eigendecomposition
Av = &#955;v  <=> A = Vdiag(&#955;)V<sup>-1</sup> (A must be square matrix.)

In [145]:
w, v = np.linalg.eig(np.diag((1, 2, 3))) 
w # eigenvalues

array([ 1.,  2.,  3.])

In [146]:
v # normalized eigenvectors

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### Singular Value Decomposition (SVD)
More generally applicable than eigendecomposition<br/>
A = UDV<sup>T</sup>

In [148]:
a = np.random.randn(9, 6) + 1j*np.random.randn(9, 6)
U, s, V = np.linalg.svd(a, full_matrices=True)
S = np.zeros((9, 6), dtype=complex)
S[:6, :6] = np.diag(s)
np.allclose(a, np.dot(U, np.dot(S, V)))

True

## Other

In [151]:
# trace operator: the sum of the elements on the main diagonal 
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [152]:
np.trace(a)

3

In [153]:
# determinant: equal to the product of all the eigenvalues of the matrix
a = np.array([[1, 2], [3, 4]])
np.linalg.det(a)

-2.0000000000000004

In [158]:
w, v = np.linalg.eig(a)
np.prod(w)

-1.9999999999999998