# Linear Algebra

In [17]:
import numpy as np
# scalar
3
# vector
np.array([1,2,3]).reshape([3, 1])

array([[1],
       [2],
       [3]])

In [18]:
# matrix
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# matrix transpose
np.transpose(m) # or m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
# tennsor
# for example: NHWC image representation

In [21]:
# matrix multiplying
m_1 = np.array([[1, 2], [1, 2]])
m_2 = np.array([[3, 4], [3, 4]])
m_1 * m_2 # elementwise product

array([[3, 8],
       [3, 8]])

In [22]:
np.dot(m_1, m_2)

array([[ 9, 12],
       [ 9, 12]])

In [23]:
# identity matrix
np.identity(3) # equal to np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
# inverse matrix
a = np.array([[1, 2], [3, 4]])
a_inv = np.linalg.inv(a)
a_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [30]:
np.dot(a, a_inv) # output should be identity matrix

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [31]:
np.allclose(np.dot(a, a_inv), np.eye(2))

True

In [32]:
np.allclose(np.dot(a_inv, a), np.eye(2))

True

    Ax = b has a solution <=> rank(A,b) = rank(A) <=> b belongs to column space
    matrix rank == range of column space == range of row space

In [34]:
# get matrix rank by SVD
np.linalg.matrix_rank(a)

2

In [37]:
# norms
a = np.array([[1, 2], [3, 4]])
np.linalg.norm(a) # defaults to L2 norm(Frobenius norm)

5.4772255750516612

In [38]:
# L1 norm
np.linalg.norm(a, ord=1)

6.0

In [39]:
# L infinity
np.linalg.norm(a, ord=np.inf)

7.0

In [42]:
# Diagonal matrices
a = np.array([[1, 2], [3, 4]])
a.diagonal()

array([1, 4])